# Stress and Strain in California: The Pinon Flat Observatory


<img src="https://scripps.ucsd.edu/sites/default/files/2020-09/PFO_TRAILER_sm.jpg" style="width:400px" />


In [1]:
# Imports
import matplotlib.pyplot as plt
import numpy as np
from numpy import linalg as la

### The University of California is running an observatory that is measuring deformations: 

a)	at 5km depth the seismic velocities are vp=6km/s, vs=3.5km/s and the density is 2700kg/m3. Calculate the values of the Lamé parameters in Pascal. 

We need:
$ v_p = \sqrt{\frac{\lambda + 2 \mu}{\rho}} $, 
to obtain
$ \lambda = \rho v_p^2 - 2 \mu $, 
wegen 
$ v_s = \sqrt{\frac{\mu}{\rho}} $, 
$ \mu = \rho v_s^2 $, 
we obtain:

$ \lambda = \rho v_p^2 - 2 \rho v_s^2 $


In [2]:
vp = 6000.    # m/s
vs = 3500.    # m/s
ro = 2700.0   # kg/m**3

lam = ro * vp**2 - 2 * ro * vs**2
mu = ro * vs**2

print('Lame Parameters: ')
print(' 1: Lambda ')
print(lam,' Pa ')
print(lam/1000000,' MPa ')
print(lam/1000000000,' GPa ')
print(' 1: Mu ')
print(mu,' Pa ')
print(mu/1000000,' MPa ')
print(mu/1000000000,' GPa ')

Lame Parameters: 
 1: Lambda 
31050000000.0  Pa 
31050.0  MPa 
31.05  GPa 
 1: Mu 
33075000000.0  Pa 
33075.0  MPa 
33.075  GPa 


b)	After the Landers earthquake 1992 (M7.3) the following deformations were measured 80km to the north of the observatory: e11=-0.26x10-6, e12=-0.69x10-6, e22=0.92x10-6. Indices 1 and 2 correspond to East and North, resp. Calculate – assuming that these values are also true at depth – the changes in stress at 5km depth with the results from (a). Treat this is a 2D problem and neglect stress in vertical direction. 



Solution: The stress-strain relation is given as 

$ \sigma_{ij} = \epsilon_{ij}\delta_{ij} \lambda + 2 \mu \epsilon_{ij} $ 

in our case we can restrict ourselves to 2D. In this case a diagonal element is 

$ \sigma_{11} = \lambda (\epsilon_{11} + \epsilon_{yy}) + 2 \mu \epsilon_{11} $

and a non-diagonal element would be 

$ \sigma_{12} =  2 \mu \epsilon_{12} $


In [3]:
# Initialize strains
e11 = -0.26e-6
e12 = -0.69e-6
e22=0.92e-6

# calculate stress changes
s11 = lam * (e11 + e22) + 2* mu *e11
s22 = lam * (e11 + e22) + 2* mu *e22
s12 = 2*mu * e12

print(' Stresses (Pa)')
print('s11 = ',s11)
print('s22 = ',s22)
print('s12 = ',s12)


 Stresses (Pa)
s11 =  3294.0
s22 =  81351.0
s12 =  -45643.5


c)	Calculate the dominant stress directions (horizontal as azimuth over North). Remember this is an eigenvalue problem. 


We need to solve an eigenvalue problem 

 $\sigma_{ij} x_j  = \lambda x_j $ 
 
to obtain two eigenvalues and the eigenvectors. We use the numpy-linalg routine "eig" for this. 

In [4]:
# Calculate eigenvalues and eigenvectors for s

# initialize 2D tensor
s = np.zeros((2,2))
s[0,0] = s11
s[1,1] = s22
s[0,1] = s12
s[1,0] = s12

print(' Stress tensor ')
print(s)

w,v = la.eig(s)

# Eigenvalues:
print('Eigenvalues')
print(' 1 : ',w[0])
print(' 2 : ',w[1])

# Eigenvectors:
print('Eigenvectors')
print(' 1 : ',v[:,0])
print(' 2 : ',v[:,1])


 Stress tensor 
[[  3294.  -45643.5]
 [-45643.5  81351. ]]
Eigenvalues
 1 :  -17732.08271023119
 2 :  102377.0827102312
Eigenvectors
 1 :  [-0.90826312 -0.41839945]
 2 :  [ 0.41839945 -0.90826312]



d)	The yearly deformation rates were measured as: e11=0.101x10-6, e12=0.005x10-6, e22=-0.02x10-6. Assume that this deformation continues for 1000 years. Calculate the stress change at 5km depth using results from a). 



In [5]:
# Initialize strains
e11 = 0.101e-6 * 1000
e12 = 0.005e-6 * 1000
e22=  -0.02e-6 * 1000

# calculate stress changes
s11 = lam * (e11 + e22) + 2* mu *e11
s22 = lam * (e11 + e22) + 2* mu *e22
s12 = 2*mu * e12

print(' Stresses (Pa)')
print('s11 = ',s11)
print('s22 = ',s22)
print('s12 = ',s12)

 Stresses (Pa)
s11 =  9196200.0
s22 =  1192050.0
s12 =  330750.0


e)	A farmer owns 1km2 near the observatory. How much land does he win or loose every year? How much land did he win or loose with the Landers earthquake? 

In [6]:
# Annual Change


# Initialize strains
e11 = 0.101e-6
e12 = 0.005e-6
e22=  -0.02e-6


# initialize 2D tensor
e = np.zeros((2,2))
e[0,0] = e11
e[1,1] = e22
e[0,1] = e12
e[1,0] = e12

print(' Deformation tensor ')
print(e)

w,v = la.eig(e)

# Eigenvalues:
print('Eigenvalues')
print(' 1 : ',w[0])
print(' 2 : ',w[1])

# Eigenvectors:
print('Eigenvectors')
print(' 1 : ',v[:,0])
print(' 2 : ',v[:,1])

 Deformation tensor 
[[ 1.01e-07  5.00e-09]
 [ 5.00e-09 -2.00e-08]]
Eigenvalues
 1 :  1.0120625997374574e-07
 2 :  -2.0206259973745707e-08
Eigenvectors
 1 :  [0.99915022 0.04121694]
 2 :  [-0.04121694  0.99915022]


Old surface is 1000m x 1000m 

Surface after one year is (1000m + ev1 x 1000m) x  (1000m + ev2 x 1000m)

In [7]:
print(' Old surface ',1000*1000,'m**2')
print(' New surface ',(1000+1000*w[0])*(1000+1000*w[1]),'m)**2')

 Old surface  1000000 m**2
 New surface  1000000.080999998 m)**2


In [8]:
# Landers


# Initialize strains
e11 = -0.26e-6
e12 = -0.69e-6
e22=0.92e-6

# initialize 2D tensor
e = np.zeros((2,2))
e[0,0] = e11
e[1,1] = e22
e[0,1] = e12
e[1,0] = e12

print(' Deformation tensor ')
print(e)

w,v = la.eig(e)

# Eigenvalues:
print('Eigenvalues')
print(' 1 : ',w[0])
print(' 2 : ',w[1])

# Eigenvectors:
print('Eigenvectors')
print(' 1 : ',v[:,0])
print(' 2 : ',v[:,1])

print(' Old surface ',1000*1000,'m**2')
print(' New surface ',(1000+1000*w[0])*(1000+1000*w[1]),'m)**2')

 Deformation tensor 
[[-2.6e-07 -6.9e-07]
 [-6.9e-07  9.2e-07]]
Eigenvalues
 1 :  -5.778546139112805e-07
 2 :  1.2378546139112804e-06
Eigenvectors
 1 :  [-0.90826312 -0.41839945]
 2 :  [ 0.41839945 -0.90826312]
 Old surface  1000000 m**2
 New surface  1000000.6599992848 m)**2
